<html>
<head>
    <meta charset="UTF-8">
    <title>权限不通过提示</title>
    <link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.0.1/css/bootstrap.min.css" rel="stylesheet">
</head>
    <body>
        <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <div class="alert alert-dismissable alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4>
                           您还没有权限，请先登录！
                        </h4>
                    </div>
                </div>
            </div>
        </div>
    </body>
<#--自动跳转-->
<script>

</script>
</html>